// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using TunNetCom.AionTime.TimeLogService.Infrastructure.MultiTenancy;

namespace TunNetCom.AionTime.TimeLogService.Infrastructure.AionTimeContext.Configurations
{
    public partial class OrganizationConfiguration : IEntityTypeConfiguration<Organization>
    {
        MultiTenancyService _multiTenancyService;
        public OrganizationConfiguration(MultiTenancyService multiTenancyService) {
            _multiTenancyService = multiTenancyService;
        }
        public OrganizationConfiguration() { }
        public void Configure(EntityTypeBuilder<Organization> entity)
        {
            entity.HasIndex(c => c.Id);
            entity.HasQueryFilter(c => c.Id == _multiTenancyService.GetTenantId());
            entity.ToTable("Organization");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Organization> entity);
    }
}
