// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.AionTime.TimeLogService.Infrastructure.AionTimeContext;

#nullable disable

namespace TunNetCom.AionTime.TimeLogService.Infrastructure.AionTimeContext.Configurations
{
    public partial class WorkItemHistoryConfiguration : IEntityTypeConfiguration<WorkItemHistory>
    {
        public void Configure(EntityTypeBuilder<WorkItemHistory> entity)
        {
            entity.ToTable("WorkItemHistory");

            entity.Property(e => e.History)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.HasOne(d => d.WorkItem).WithMany(p => p.WorkItemHistories)
                .HasForeignKey(d => d.WorkItemId)
                .HasConstraintName("FKTicketHistory");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkItemHistory> entity);
    }
}
