global using MassTransit;
global using MediatR;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using RabbitMQ.Client;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Net;
global using System.Reflection;
global using System.Text;
global using System.Threading.Tasks;
global using TunNetCom.AionTime.AzureDevops.WebhookService.Application;
global using static MassTransit.Logging.DiagnosticHeaders.Messaging;