global using AutoMapper;
global using AzureDevopsService.Contracts.AzureRequestResourceModel;
global using AzureDevopsService.Contracts.AzureResponceModel;
global using MassTransit;
global using MediatR;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Newtonsoft.Json;
global using System.Collections.Generic;
global using System.Reflection;
global using TimeLogService;
global using TimeLogService.Application;
global using TimeLogService.Application.Feature;
global using TimeLogService.Application.Feature.MessageBroker;
global using TimeLogService.Application.Feature.MessageBroker.Consumer;
global using TimeLogService.Application.Feature.MessageBroker.Consumer.WebhookConsumer;
global using TimeLogService.Application.Feature.MessageBroker.Consumers;
global using TimeLogService.Application.Feature.MessageBroker.Consumers.AzureDevopsConsumer;
global using TimeLogService.Application.Feature.OrganizationAction.Commands.AddOrganization;
global using TimeLogService.Application.Feature.OrganizationAction.Commands.AddOrganizationList;
global using TimeLogService.Application.Feature.UserAction.Commands.AddUser;
global using TimeLogService.Contracts.DTOs.Request;
global using TimeLogService.Contracts.Settings;
global using TimeLogService.Domain.Interfaces.Repositories;
global using TimeLogService.Domain.Models;
global using TimeLogService.Domain.Models.Dbo;
global using WebhookService.Contracts;
global using WebhookService.Contracts.EventModels.SharedModels;
global using WebhookService.Contracts.EventModels.SharedModels.ResourcesModels;
global using static MassTransit.Logging.OperationName;
global using static Org.BouncyCastle.Math.EC.ECCurve;
global using RabbitMqSettings = TimeLogService.Contracts.Settings.RabbitMqSettings;