global using AutoMapper;
global using MassTransit;
global using MediatR;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using Newtonsoft.Json;
global using System.Reflection;
global using TimeLogService;
global using TimeLogService.Application;
global using TimeLogService.Application.Feature.RabbitMqConsumer.WebhookConsumer;
global using TimeLogService.Contracts.DTOs.Request;
global using TimeLogService.Contracts.Settings;
global using TimeLogService.Domain.Interfaces.Repositories;
global using TimeLogService.Domain.Models.Dbo;
global using TunNetCom;
global using TunNetCom.AionTime;
global using WebhookService.Contracts.EventModels.SharedModels;
global using WebhookService.Contracts.EventModels.SharedModels.ResourcesModels;
global using static MassTransit.Logging.OperationName;
global using static Org.BouncyCastle.Math.EC.ECCurve;
global using RabbitMqSettings = TimeLogService.Contracts.Settings.RabbitMqSettings;