// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.AionTime.AzureDevopsService.API.Data;
using TunNetCom.AionTime.AzureDevopsService.API.Entites;

#nullable disable

namespace TunNetCom.AionTime.AzureDevopsService.API.Data.Configurations
{
    public partial class AzureDevopsHistoryConfiguration : IEntityTypeConfiguration<AzureDevopsHistory>
    {
        public void Configure(EntityTypeBuilder<AzureDevopsHistory> entity)
        {
            entity.ToTable("AzureDevopsHistory");

            entity.Property(e => e.Email).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AzureDevopsHistory> entity);
    }
}
