// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.AionTime.AzureDevopsService.API.Data;
using TunNetCom.AionTime.AzureDevopsService.API.Entites;

#nullable disable

namespace TunNetCom.AionTime.AzureDevopsService.API.Data.Configurations
{
    public partial class OrganizationConfiguration : IEntityTypeConfiguration<Organization>
    {
        public void Configure(EntityTypeBuilder<Organization> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07DE523F87");

            entity.ToTable("Organization");

            entity.HasIndex(e => e.Name, "IX_Organization_Name_Unique").IsUnique();

            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Pat).HasMaxLength(150);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Organization> entity);
    }
}
