// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunNetCom.AionTime.TimeLogService.Domain.Models;

[Table("TicketTimeLog")]
public partial class TicketTimeLog
{
    [Key]
    public int TicketTimeLogId { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string LogDescription { get; set; }

    public DateOnly LogTime { get; set; }

    public int TicketId { get; set; }

    [ForeignKey("TicketId")]
    [InverseProperty("TicketTimeLogs")]
    public virtual Ticket Ticket { get; set; }
}