// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunNetCom.AionTime.TimeLogService.Domain.Models;

[Table("Ticket")]
public partial class Ticket
{
    [Key]
    public int TicketId { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string TicketDiscription { get; set; }

    public int ProjectId { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("Tickets")]
    public virtual Project Project { get; set; }

    [InverseProperty("Ticket")]
    public virtual ICollection<TicketHistory> TicketHistories { get; set; } = new List<TicketHistory>();

    [InverseProperty("Ticket")]
    public virtual ICollection<TicketTimeLog> TicketTimeLogs { get; set; } = new List<TicketTimeLog>();
}