// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunNetCom.AionTime.TimeLogService.Domain.Models;

[Table("WorkItemHistory")]
public partial class WorkItemHistory
{
    [Key]
    public int WorkItemHistoryId { get; set; }

    [Column("WorkItemHistory")]
    [StringLength(1000)]
    [Unicode(false)]
    public string WorkItemHistory1 { get; set; }

    public int WorkItemId { get; set; }

    [ForeignKey("WorkItemId")]
    [InverseProperty("WorkItemHistories")]
    public virtual WorkItem WorkItem { get; set; }
}