// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TunNetCom.AionTime.TimeLogService.Domain.Models;

[Table("WorkItem")]
public partial class WorkItem
{
    [Key]
    public int WorkItemId { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string WorkItemDiscription { get; set; }

    public int ProjectId { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("WorkItems")]
    public virtual Project Project { get; set; }

    [InverseProperty("WorkItem")]
    public virtual ICollection<WorkItemHistory> WorkItemHistories { get; set; } = new List<WorkItemHistory>();

    [InverseProperty("WorkItem")]
    public virtual ICollection<WorkItemTimeLog> WorkItemTimeLogs { get; set; } = new List<WorkItemTimeLog>();
}