global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;