global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System;
global using TimeLogService.Infrastructure.AionTimeContext;
global using TimeLogService.Infrastructure.MultiTenancy;
global using TimeLogService.Infrastructure.AionTimeContext.Configurations;
