name: CI

on:
  # Triggers the workflow on pull request events for the "master" branch
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Add automatic reviewer to pull request
      - name: Add Automatic Reviewer
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = github.context.payload.repository.owner.login;
            const repo = github.context.payload.repository.name;
            const prNumber = github.context.payload.pull_request.number;
            const reviewer = 'Nieze-BenMansour'; // Specify the username of the reviewer

            await github.pulls.createReviewRequest({
              owner: owner,
              repo: repo,
              pull_number: prNumber,
              reviewers: [reviewer]
            });

      # Other steps for building, testing, and deploying your project
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
