// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using TunNetCom.AionTime.AzureDevopsService.API.Data.Configurations;
using TunNetCom.AionTime.AzureDevopsService.API.Entites;
#nullable enable

namespace TunNetCom.AionTime.AzureDevopsService.API.Data;

public partial class AzureDevOpsContext : DbContext
{
    public AzureDevOpsContext(DbContextOptions<AzureDevOpsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AzureDevopsHistory> AzureDevopsHistories { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.AzureDevopsHistoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrganizationConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
