// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.AionTime.AzureDevopsService.API.Entites;

public partial class AzureDevopsHistory
{
    public int Id { get; set; }

    public int? ActionType { get; set; }

    public string? Email { get; set; }

    public DateOnly? ActionDate { get; set; }
}