// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.AionTime.AzureDevopsService.API.Entites;

public partial class Organization
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Pat { get; set; } = null!;
}